version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "8000:8000"

  recetas:
    container_name: recetas
    restart: always
    build: ./recetas
    ports:
      - "8001:8001"

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - "8002:8002"

  users:
    container_name: users
    restart: always
    build: ./users
    ports:
      - "8003:8003"

  auth:
    container_name: auth
    restart: always
    build: ./auth
    ports:
      - "8004:8004"