version: '3'

services:
  gateway:
    container_name: MicroservicioGateway
    restart: always
    build: ./MicroservicioGateway
    ports:
      - "8000:8000"

  recetas:
    container_name: recetas
    restart: always
    build: ./MicroservicioRecetas
    ports:
      - "8001:8001"

  users:
    container_name: recetas
    restart: always
    build: ./MicroservicioUsers
    ports:
      - "8002:8002"

  auth:
    container_name: dbrecetas
    restart: always
    build: ./MicroservicioAuth
    ports:
      - "8003:8003"

  dbrecetas:
    container_name: dbrecetas
    restart: always
    build: ./MicroservicioDB
    ports:
      - "8004:8004"